import { Mission, DemoSession } from "./types";
import { getMissionDueDateISO } from "./dates";

export const SEED_MISSIONS: Mission[] = [
  {
    id: "mission-0",
    number: 0,
    title: "Setup",
    description: "Folders, accounts, rubric saved",
    category: "Foundation",
    status: "not_started",
    dueDate: getMissionDueDateISO(0),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-1",
    number: 1,
    title: "Resolution Tracker",
    description: "Build a working web app that tracks progress through the 10 weekends",
    category: "Foundation",
    status: "not_started",
    dueDate: getMissionDueDateISO(1),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-2",
    number: 2,
    title: "Model Topography",
    description: "Topography Sheet + Rules of Thumb for AI models",
    category: "Foundation",
    status: "not_started",
    dueDate: getMissionDueDateISO(2),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-3",
    number: 3,
    title: "Deep Research Brief",
    description: "2 pages, clear recommendation using deep research",
    category: "Core Projects",
    status: "not_started",
    dueDate: getMissionDueDateISO(3),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-4",
    number: 4,
    title: "Data Analysis Memo",
    description: "Cleaned data, 3 insights, 3 actions",
    category: "Core Projects",
    status: "not_started",
    dueDate: getMissionDueDateISO(4),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-5",
    number: 5,
    title: "Visual Explainer",
    description: "One infographic you'd actually use",
    category: "Core Projects",
    status: "not_started",
    dueDate: getMissionDueDateISO(5),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-6",
    number: 6,
    title: "Information Pipeline",
    description: "Summary + FAQ + Deck from source material",
    category: "Core Projects",
    status: "not_started",
    dueDate: getMissionDueDateISO(6),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-7",
    number: 7,
    title: "First Automation",
    description: "Content workflow working end-to-end",
    category: "Automation",
    status: "not_started",
    dueDate: getMissionDueDateISO(7),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-8",
    number: 8,
    title: "Second Automation",
    description: "Productivity workflow working end-to-end",
    category: "Automation",
    status: "not_started",
    dueDate: getMissionDueDateISO(8),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-9",
    number: 9,
    title: "Personal Context OS",
    description: "Context Docs + Capture system built",
    category: "System & Build",
    status: "not_started",
    dueDate: getMissionDueDateISO(9),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-10",
    number: 10,
    title: "AI-Powered Build",
    description: "Chatbot or Agent deployed and working",
    category: "System & Build",
    status: "not_started",
    dueDate: getMissionDueDateISO(10),
    completedAt: null,
    notes: "",
  },
  {
    id: "mission-bonus",
    number: 11,
    title: "Agent Evaluation Gauntlet",
    description: "Scorecard completed + Best use cases identified",
    category: "Bonus",
    status: "not_started",
    dueDate: getMissionDueDateISO(11),
    completedAt: null,
    notes: "",
  },
];

export const SEED_DEMO_SESSIONS: DemoSession[] = Array.from({ length: 10 }, (_, i) => ({
  id: `demo-${i + 1}`,
  sessionNumber: i + 1,
  missionId: `mission-${i + 1}`,
  date: null,
  didDemo: false,
  rippleEffect: "",
}));
